from __future__ import annotations

import os
import sys
from pathlib import Path


KQK_OUTPUT_ROOT = Path(r"C:\Users\Κωνσταντίνος\Desktop\KQK Dataset")


def open_folder_if_supported(folder: Path) -> None:
    """Open the output folder in the OS file manager if running on Windows."""
    if sys.platform.startswith("win") and hasattr(os, "startfile"):
        os.startfile(folder)


def write_project_readme(output_root: Path) -> None:
    output_root.mkdir(parents=True, exist_ok=True)
    readme_path = output_root / "README.md"

    readme_lines = [
        "# KQK Endgame Analysis — Παραγωγή Κανόνων με Decision Trees",
        "",
        "Αυτός ο φάκελος περιέχει την πλήρη πειραματική ενότητα για το σκακιστικό φινάλε **KQK**.",
        "",
        "Το KQK endgame αποτελείται από:",
        "",
        "- λευκό βασιλιά,",
        "- λευκή βασίλισσα,",
        "- μαύρο βασιλιά.",
        "",
        "Ο στόχος της ενότητας δεν είναι η απλή ταξινόμηση θέσεων ως `Win` / `Draw`, αλλά η παραγωγή ερμηνεύσιμων κανόνων που περιγράφουν τη φάση μετατροπής μιας κερδισμένης KQK θέσης.",
        "",
        "Για αυτόν τον λόγο χρησιμοποιείται το `DTZ` από Syzygy tablebases και μετατρέπεται σε προσεγγιστικές φάσεις μετατροπής.",
        "",
        "",
        "## 1. Στόχος της KQK ενότητας",
        "",
        "Στο KQK, η WDL πληροφορία είναι σχετικά φτωχή για rule extraction, επειδή οι περισσότερες νόμιμες θέσεις με λευκή βασίλισσα και λευκό βασιλιά εναντίον μαύρου βασιλιά είναι θεωρητικά κερδισμένες για τον λευκό.",
        "",
        "Επομένως, αντί να προβλέπεται απλώς αν η θέση είναι κερδισμένη, το πρόβλημα μετατρέπεται σε ταξινόμηση της θέσης σε φάση μετατροπής:",
        "",
        "- `long_conversion`,",
        "- `medium_conversion`,",
        "- `short_conversion`,",
        "- `immediate_mate`.",
        "",
        "Οι φάσεις αυτές χρησιμοποιούνται ως πρακτικά labels για interpretable classification και rule extraction.",
        "",
        "",
        "## 2. DTZ-derived distance και όχι πραγματικό DTM",
        "",
        "Η στήλη `mate_moves` που χρησιμοποιείται στο dataset δεν αποτελεί άμεσο DTM label.",
        "",
        "Υπολογίζεται από το απόλυτο DTZ ως:",
        "",
        "mate_moves = (dtz_abs + 1) // 2",
        "",
        "Άρα είναι καλύτερο να ερμηνεύεται ως **DTZ-derived approximate conversion distance** και όχι ως επίσημο distance-to-mate.",
        "",
        "Στο KQK η ποσότητα αυτή είναι πρακτικά χρήσιμη για τη διακριτοποίηση των φάσεων, αλλά δεν ταυτίζεται εννοιολογικά με DTM.",
        "",
        "Οι φάσεις ορίζονται ως:",
        "",
        "immediate_mate : mate_moves <= 1",
        "short_conversion       : mate_moves 2–3",
        "medium_conversion      : mate_moves 4–6",
        "long_conversion        : mate_moves 7+",
        "",
        "Οι κατηγορίες αυτές είναι πειραματική διακριτοποίηση του DTZ-derived distance και όχι επίσημες σκακιστικές κατηγορίες.",
        "",
        "",
        "## 3. Dataset policy",
        "",
        "Το dataset παράγεται για:",
        "",
        "side_to_move = White",
        "only_winning_for_side_to_move = True",
        "",
        "Δηλαδή κρατούνται μόνο θέσεις στις οποίες η πλευρά που έχει την κίνηση, εδώ ο λευκός, είναι κερδισμένη σύμφωνα με τις Syzygy tablebases.",
        "",
        "Αυτό γίνεται επειδή ο στόχος δεν είναι WDL classification όλων των θέσεων, αλλά phase classification κερδισμένων KQK θέσεων.",
        "",
        "Αν περιλαμβάνονταν μη κερδισμένες θέσεις, τότε τα DTZ buckets δεν θα είχαν καθαρή ερμηνεία ως φάσεις μετατροπής προς το mate.",
        "",
        "",
        "## 4. Δομή project",
        "",
        "KQK Dataset/",
        "├── 01_dataset/",
        "│   ├── kqk_exhaustive_dtz_dataset.csv",
        "│   └── kqk_dataset_overview.csv",
        "│",
        "├── 02_model_dtz/",
        "│   ├── kqk_dtz_decision_tree_main_model_summary.csv",
        "│   ├── kqk_dtz_decision_tree_main_model_importances.csv",
        "│   ├── kqk_dtz_decision_tree_confusion_matrix.csv",
        "│   ├── kqk_dtz_decision_tree_multi_seed_raw_results.csv",
        "│   ├── kqk_dtz_decision_tree_multi_seed_stability_summary.csv",
        "│   ├── kqk_dtz_decision_tree_depth_selection_scores.csv",
        "│   ├── kqk_dtz_decision_tree_selected_optimal_depth.csv",
        "│   ├── kqk_dtz_decision_tree_all_leaf_rules.csv",
        "│   ├── kqk_dtz_decision_tree_important_rules.csv",
        "│   ├── kqk_dtz_decision_tree_raw_errors.csv",
        "│   ├── kqk_dtz_decision_tree_categorized_errors.csv",
        "│   ├── kqk_dtz_decision_tree_error_category_counts.csv",
        "│   ├── kqk_dtz_decision_tree_error_type_counts.csv",
        "│   ├── kqk_dtz_decision_tree_error_flag_counts.csv",
        "│   ├── kqk_dtz_decision_tree_error_severity_counts.csv",
        "│   ├── kqk_dtz_decision_tree_phase_confusion_counts.csv",
        "│   ├── kqk_dtz_decision_tree_errors_by_dtz_abs.csv",
        "│   ├── kqk_dtz_decision_tree_errors_by_mate_moves.csv",
        "│   ├── kqk_dtz_decision_tree_tree_rules.txt",
        "│   └── kqk_dtz_decision_tree_summary_report.md",
        "│",
        "├── 03_feature_set_comparison/",
        "│   ├── kqk_feature_set_comparison_raw_results.csv",
        "│   ├── kqk_feature_set_comparison_stability_summary.csv",
        "│   ├── kqk_feature_set_comparison_main_depth{N}_{class_weight}_comparison.csv",
        "│   ├── kqk_feature_set_comparison_main_config_used.csv",
        "│   ├── kqk_feature_set_comparison_raw_importances.csv",
        "│   ├── kqk_feature_set_comparison_mean_importances.csv",
        "│   ├── kqk_feature_set_comparison_error_categories_raw.csv",
        "│   └── kqk_feature_set_comparison_error_category_summary.csv",
        "│",
        "├── 04_figures/",
        "│   ├── kqk_dataset_distribution.png",
        "│   ├── kqk_decision_tree_top3.png",
        "│   ├── kqk_feature_importances.png",
        "│   ├── kqk_confusion_matrix.png",
        "│   ├── kqk_phase_confusion_counts.png",
        "│   ├── kqk_error_categories.png",
        "│   ├── kqk_error_severity.png",
        "│   ├── kqk_errors_by_mate_moves.png",
        "│   ├── kqk_errors_by_dtz_abs.png",
        "│   ├── kqk_feature_set_comparison.png",
        "│   └── kqk_stability_across_depths.png",
        "│",
        "├── 05_rule_consolidation/",
        "│   ├── kqk_rule_consolidation_leaves_with_signature.csv",
        "│   ├── kqk_rule_consolidation_distinct_signatures.csv",
        "│   ├── kqk_rule_consolidation_top_signatures_by_phase.csv",
        "│   ├── kqk_rule_consolidation_interpretive_motifs.csv",
        "│   ├── kqk_rule_consolidation_phase_coverage.csv",
        "│   └── kqk_rule_consolidation_summary.md",
        "│",
        "└── README.md",
        "",
        "",
        "## 5. Σειρά εκτέλεσης",
        "",
        "Τα scripts εκτελούνται με την εξής σειρά:",
        "",
        "```bash",
        "python KQKGenerator.py",
        "python KQKDecTree.py",
        "python KQKComp.py",
        "python KQKVisual.py",
        "python KQKRuleConsolidation.py",
        "python KQKReadMe.py",
        "```",
        "",
        "Η σειρά είναι σημαντική.",
        "",
        "- Το `KQKGenerator.py` παράγει το dataset.",
        "- Το `KQKDecTree.py` εκπαιδεύει το main model και αποθηκεύει το selected configuration.",
        "- Το `KQKComp.py` διαβάζει το selected configuration και συγκρίνει feature sets.",
        "- Το `KQKVisual.py` διαβάζει επίσης το selected configuration και παράγει figures για το ίδιο μοντέλο.",
        "- Το `KQKRuleConsolidation.py` διαβάζει τα extracted leaves και παράγει binned signatures.",
        "- Το `KQKReadMe.py` εκτελείται τελευταίο για να γράψει το τελικό README.",
        "",
        "",
        "## 6. Dataset Generation",
        "",
        "Script:",
        "",
        "`KQKGenerator.py`",
        "",
        "Παράγει exhaustive KQK dataset με χρήση Syzygy tablebases.",
        "",
        "Βασικά outputs:",
        "",
        "- `01_dataset/kqk_exhaustive_dtz_dataset.csv`",
        "- `01_dataset/kqk_dataset_overview.csv`",
        "",
        "Το dataset περιλαμβάνει:",
        "",
        "- FEN θέσης,",
        "- Syzygy WDL,",
        "- Syzygy DTZ,",
        "- απόλυτη τιμή DTZ (`dtz_abs`),",
        "- DTZ-derived approximate distance (`mate_moves`),",
        "- target phase (`dtz_bucket`),",
        "- γεωμετρικά features,",
        "- chess-informed features για περιορισμό του μαύρου βασιλιά και έλεγχο από τη βασίλισσα.",
        "",
        "",
        "## 7. Τελικό Feature Set",
        "",
        "Το τελικό KQK main model χρησιμοποιεί τα εξής features:",
        "",
        "bk_legal_moves_if_black_to_move",
        "bk_distance_to_corner",
        "bk_distance_to_edge",
        "wk_distance_to_edge",
        "wk_wq_distance",
        "wk_bk_chebyshev_distance",
        "wk_bk_manhattan_distance",
        "wq_bk_chebyshev_distance",
        "queen_box_area",
        "queen_controls_bk_zone_count",
        "stalemate_risk_level",
        "",
        "Το `side_to_move` δεν χρησιμοποιείται ως feature, επειδή το dataset είναι σταθερά white to move.",
        "",
        "",
        "## 8. Περιγραφή βασικών KQK features",
        "",
        "- `bk_legal_moves_if_black_to_move`: αριθμός νόμιμων κινήσεων του μαύρου βασιλιά αν είχε τη σειρά.",
        "- `bk_distance_to_corner`: απόσταση του μαύρου βασιλιά από την κοντινότερη γωνία.",
        "- `bk_distance_to_edge`: απόσταση του μαύρου βασιλιά από την κοντινότερη άκρη.",
        "- `wk_distance_to_edge`: απόσταση του λευκού βασιλιά από άκρη.",
        "- `wk_wq_distance`: Chebyshev απόσταση μεταξύ λευκού βασιλιά και βασίλισσας.",
        "- `wk_bk_chebyshev_distance`: Chebyshev απόσταση μεταξύ των δύο βασιλιάδων.",
        "- `wk_bk_manhattan_distance`: Manhattan απόσταση μεταξύ των δύο βασιλιάδων.",
        "- `wq_bk_chebyshev_distance`: Chebyshev απόσταση μεταξύ βασίλισσας και μαύρου βασιλιά.",
        "- `queen_box_area`: προσεγγιστική επιφάνεια του χώρου στον οποίο έχει περιοριστεί ο μαύρος βασιλιάς από τη βασίλισσα.",
        "- `queen_controls_bk_zone_count`: πόσα τετράγωνα γύρω από τον μαύρο βασιλιά ελέγχονται από τη βασίλισσα.",
        "- `stalemate_risk_level`: chess-informed diagnostic feature για πιθανό κίνδυνο stalemate.",
        "",
        "Το `stalemate_risk_level` δεν είναι Syzygy label. Είναι handcrafted interpretability feature, σχεδιασμένο για να αποτυπώνει πρακτικά μοτίβα προσοχής στο KQK.",
        "",
        "",
        "## 9. Main Decision Tree Model",
        "",
        "Script:",
        "",
        "`KQKDecTree.py`",
        "",
        "Εκπαιδεύει decision tree για ταξινόμηση των KQK θέσεων στις τέσσερις DTZ-derived φάσεις.",
        "",
        "Σταθερές ρυθμίσεις:",
        "",
        "seed = 42",
        "criterion = gini",
        "min_samples_split = 50",
        "min_samples_leaf = 25",
        "",
        "Το `max_depth` και το `class_weight` δεν είναι hardcoded. Επιλέγονται αυτόματα από grid:",
        "",
        "max_depth: [7, 9, 12]",
        "class_weight: [None, balanced]",
        "",
        "Η επιλογή γίνεται με adjusted score:",
        "",
        "adjusted_score = balanced_accuracy_mean − penalty_weight × sqrt(n_leaves_mean / max_n_leaves_mean)",
        "",
        "Το score επιβραβεύει υψηλή balanced accuracy και ποινικοποιεί την πολυπλοκότητα του δέντρου, ώστε να προτιμώνται πιο ερμηνεύσιμα μοντέλα όταν η επίδοση είναι παρόμοια.",
        "",
        "Η παράμετρος `penalty_weight = 0.01` είναι heuristic επιλογή για model selection και όχι θεωρητικό metric.",
        "",
        "Το selected configuration αποθηκεύεται στο:",
        "",
        "- `02_model_dtz/kqk_dtz_decision_tree_selected_optimal_depth.csv`",
        "",
        "Αυτό το αρχείο διαβάζεται από τα `KQKComp.py` και `KQKVisual.py`, ώστε όλο το pipeline να χρησιμοποιεί το ίδιο main configuration.",
        "",
        "",
        "## 10. Μεθοδολογική σημείωση για model selection",
        "",
        "Η επιλογή του main model βασίζεται σε multi-seed evaluation και adjusted score.",
        "",
        "Για λόγους διαφάνειας, το pipeline αναφέρει επίσης cross-validation metrics:",
        "",
        "- CV accuracy,",
        "- CV balanced accuracy,",
        "- CV macro F1.",
        "",
        "Το single-split test score πρέπει να ερμηνεύεται ως diagnostic/secondary ένδειξη επίδοσης και όχι ως μοναδική ανεξάρτητη benchmark μέτρηση.",
        "",
        "Ο κύριος στόχος της ενότητας είναι η παραγωγή και ερμηνεία κανόνων και όχι η παρουσίαση ενός αυστηρού benchmark γενίκευσης.",
        "",
        "",
        "## 11. Ordinal φύση του target",
        "",
        "Οι κλάσεις του `dtz_bucket` έχουν φυσική σειρά:",
        "",
        "long_conversion → medium_conversion → short_conversion → immediate_mate",
        "",
        "Παρόλα αυτά χρησιμοποιείται `DecisionTreeClassifier` ως nominal classifier.",
        "",
        "Η επιλογή αυτή είναι σκόπιμη, επειδή ο βασικός στόχος είναι η εξαγωγή ανθρώπινα αναγνώσιμων κανόνων ανά φάση και όχι η βελτιστοποίηση ordinal loss.",
        "",
        "Η ordinal φύση του προβλήματος αξιολογείται εκ των υστέρων μέσω phase-distance error analysis, όπου διακρίνονται boundary confusions από large phase confusions.",
        "",
        "",
        "## 12. Feature Set Comparison",
        "",
        "Script:",
        "",
        "`KQKComp.py`",
        "",
        "Συγκρίνει τρία feature sets:",
        "",
        "1. `raw_coordinates`",
        "2. `geometric_features`",
        "3. `full_kqk_strategic_features`",
        "",
        "Το `raw_coordinates` αποτελεί baseline με τις απλές συντεταγμένες των κομματιών.",
        "",
        "Το `geometric_features` χρησιμοποιεί αποστάσεις και γεωμετρικές σχέσεις.",
        "",
        "Το `full_kqk_strategic_features` προσθέτει chess-informed πληροφορία, όπως κινητικότητα μαύρου βασιλιά, queen control και stalemate risk.",
        "",
        "Ο main comparison πίνακας παρουσιάζεται στο ίδιο `(depth, class_weight)` που επέλεξε το `KQKDecTree.py`, ώστε να απομονώνεται η επίδραση των features.",
        "",
        "Το όνομα του main comparison αρχείου είναι δυναμικό, π.χ.:",
        "",
        "kqk_feature_set_comparison_main_depth{N}_{class_weight}_comparison.csv",
        "",
        "Παράγεται επίσης:",
        "",
        "- `kqk_feature_set_comparison_main_config_used.csv`",
        "",
        "ώστε να καταγράφεται αν το configuration προήλθε αυτόματα από το `KQKDecTree.py` ή από fallback.",
        "",
        "",
        "## 13. Visualizations",
        "",
        "Script:",
        "",
        "`KQKVisual.py`",
        "",
        "Παράγει εικόνες για παρουσίαση:",
        "",
        "- κατανομή buckets και DTZ-derived approximate distance,",
        "- top levels του decision tree,",
        "- feature importances,",
        "- confusion matrix,",
        "- phase confusions,",
        "- error categories,",
        "- error severity,",
        "- errors by mate_moves / dtz_abs,",
        "- feature-set comparison,",
        "- stability across depths.",
        "",
        "Το `KQKVisual.py` διαβάζει το selected configuration από το `KQKDecTree.py`.",
        "",
        "Έτσι το visualized tree, το feature-set comparison figure και το stability plot αντιστοιχούν στο ίδιο main model configuration.",
        "",
        "Το πλήρες decision tree δεν είναι πρακτικά ευανάγνωστο, επομένως στις οπτικοποιήσεις παρουσιάζονται μόνο τα ανώτερα επίπεδα.",
        "",
        "",
        "## 14. Παραγόμενοι Κανόνες",
        "",
        "Τα σημαντικότερα αρχεία για την παραγωγή κανόνων είναι:",
        "",
        "- `02_model_dtz/kqk_dtz_decision_tree_important_rules.csv`",
        "- `02_model_dtz/kqk_dtz_decision_tree_all_leaf_rules.csv`",
        "",
        "Κάθε κανόνας περιλαμβάνει:",
        "",
        "- `technical_rule`: ακριβής κανόνας του decision tree με thresholds.",
        "- `readable_rule`: ίδιος κανόνας με πιο αναγνώσιμα feature names.",
        "- `human_readable_rule`: φυσική γλωσσική απόδοση του κανόνα.",
        "- `rule_summary`: σύντομη σκακιστική ερμηνεία του κανόνα.",
        "- `strategic_interpretation`: ερμηνεία της προβλεπόμενης KQK φάσης.",
        "- `strategic_guidance`: στρατηγικός στόχος για τη συγκεκριμένη φάση.",
        "",
        "Οι κανόνες είναι machine-learned approximations από tablebase data και όχι τυπικά σκακιστικά θεωρήματα.",
        "",
        "",
        "## 15. Rule Consolidation — Auto-Extracted Binned Signatures",
        "",
        "Script:",
        "",
        "`KQKRuleConsolidation.py`",
        "",
        "Το decision tree μπορεί να παράγει πολλά leaf rules. Το rule consolidation τα μετατρέπει σε πιο συμπαγή και αναγνώσιμα patterns.",
        "",
        "Η τελική προσέγγιση έχει δύο επίπεδα:",
        "",
        "1. **Objective / data-driven layer**",
        "",
        "   Τα decision-tree leaves μετατρέπονται σε binned signatures. Κάθε signature προκύπτει αυτόματα από τα thresholds του δέντρου και ομαδοποιείται με βάση:",
        "",
        "   predicted_phase + binned_signature",
        "",
        "2. **Interpretive layer**",
        "",
        "   Σε κάθε signature αποδίδεται προαιρετικά ανθρώπινη σκακιστική ερμηνεία, όπως corner/edge pressure, compact queen box, stalemate caution ή queen activity.",
        "",
        "Το interpretive label δεν καθορίζει την κύρια ομαδοποίηση. Η κύρια ομαδοποίηση παραμένει data-driven.",
        "",
        "Κύρια outputs:",
        "",
        "- `05_rule_consolidation/kqk_rule_consolidation_leaves_with_signature.csv`",
        "- `05_rule_consolidation/kqk_rule_consolidation_distinct_signatures.csv`",
        "- `05_rule_consolidation/kqk_rule_consolidation_top_signatures_by_phase.csv`",
        "- `05_rule_consolidation/kqk_rule_consolidation_interpretive_motifs.csv`",
        "- `05_rule_consolidation/kqk_rule_consolidation_phase_coverage.csv`",
        "- `05_rule_consolidation/kqk_rule_consolidation_summary.md`",
        "",
        "Για το KQK, τα dominant motifs στις κοντινές φάσεις περιγράφουν κυρίως:",
        "",
        "- πίεση σε άκρη ή γωνία,",
        "- μικρό queen box,",
        "- κίνδυνο stalemate και ανάγκη ακρίβειας,",
        "- υποστήριξη του λευκού βασιλιά,",
        "- ενεργό ρόλο της βασίλισσας στη ζώνη του μαύρου βασιλιά.",
        "",
        "",
        "## 16. Μεθοδολογία Αξιολόγησης",
        "",
        "Το μοντέλο αξιολογείται με:",
        "",
        "- accuracy,",
        "- balanced accuracy,",
        "- macro F1,",
        "- weighted F1,",
        "- confusion matrix,",
        "- cross-validation metrics,",
        "- multi-seed stability,",
        "- depth/class-weight selection diagnostic,",
        "- error category analysis,",
        "- feature set comparison.",
        "",
        "Το βασικό metric που τονίζεται είναι το `balanced accuracy`, επειδή το `dtz_bucket` target μπορεί να μην είναι ισορροπημένο ανά φάση.",
        "",
        "",
        "## 17. Error Analysis",
        "",
        "Τα λάθη κατηγοριοποιούνται με βάση το αν το μοντέλο προέβλεψε τη θέση πιο κοντά ή πιο μακριά από την τελική μετατροπή σε σχέση με το πραγματικό DTZ bucket.",
        "",
        "Βασικά error types:",
        "",
        "predicted_too_close_to_mate",
        "predicted_too_far_from_mate",
        "",
        "Επιπλέον, υπολογίζεται phase distance:",
        "",
        "phase_distance = predicted_phase_rank - true_phase_rank",
        "absolute_phase_distance = |phase_distance|",
        "",
        "Έτσι διακρίνονται:",
        "",
        "- boundary confusions, όπως `long ↔ medium` ή `short ↔ immediate`,",
        "- large confusions, όπως `long ↔ immediate`.",
        "",
        "Ενδεικτικά diagnostic labels:",
        "",
        "- `long_medium_boundary_confusion`,",
        "- `medium_short_boundary_confusion`,",
        "- `short_immediate_boundary_confusion`,",
        "- `large_phase_confusion`,",
        "- `black_king_freedom_overestimated_as_restriction`,",
        "- `edge_distance_overestimated_as_restriction`,",
        "- `corner_distance_overestimated_as_restriction`,",
        "- `queen_box_size_underestimated`,",
        "- `queen_box_restriction_underestimated`,",
        "- `queen_control_overestimated`,",
        "- `queen_control_underestimated`,",
        "",
        "Οι κατηγορίες αυτές είναι diagnostic labels για ερμηνεία των λαθών και όχι τυπικές σκακιστικές αποδείξεις.",
        "",
        "",
        "## 18. Κύρια Ερμηνεία για τη Διπλωματική",
        "",
        "Τα KQK πειράματα μπορούν να υποστηρίξουν τα εξής:",
        "",
        "1. Η απλή WDL ταξινόμηση δεν δίνει αρκετά πλούσια πληροφορία για παραγωγή κανόνων στο KQK.",
        "2. Η χρήση DTZ-derived phase buckets επιτρέπει rule extraction για διαφορετικά στάδια τεχνικής μετατροπής.",
        "3. Τα raw coordinates παρέχουν baseline, αλλά τα geometric και chess-informed features είναι πιο κατάλληλα για ερμηνεύσιμους κανόνες.",
        "4. Τα στρατηγικά KQK features αποτυπώνουν περιορισμό του μαύρου βασιλιά, queen box, queen control, king coordination και stalemate risk.",
        "5. Το rule consolidation παράγει πρώτα data-driven binned signatures και μετά optional ανθρώπινα ερμηνευτικά labels.",
        "6. Τα downstream scripts χρησιμοποιούν το ίδιο selected model configuration, ώστε τα metrics, comparisons και figures να είναι μεταξύ τους συνεπή.",
        "",
        "",
        "## 19. Προειδοποίηση Ερμηνείας",
        "",
        "Οι κανόνες που εξάγονται από το decision tree είναι machine-learned approximations.",
        "",
        "Πρέπει να ερμηνεύονται ως ερμηνεύσιμοι κανόνες που έμαθε το μοντέλο από tablebase δεδομένα και όχι ως τυπικά σκακιστικά θεωρήματα.",
        "",
        "Επιπλέον:",
        "",
        "- τα DTZ buckets είναι πειραματική διακριτοποίηση,",
        "- το `mate_moves` είναι DTZ-derived approximation και όχι πραγματικό DTM,",
        "- το `stalemate_risk_level` είναι handcrafted diagnostic feature,",
        "- το decision tree είναι nominal classifier, ενώ η ordinal φύση των phases αξιολογείται post-hoc μέσω phase-distance analysis.",
    ]

    readme = "\n".join(readme_lines)
    readme_path.write_text(readme, encoding="utf-8")

    print("README saved successfully.")
    print("Path:")
    print(readme_path)
    print("Exists:", readme_path.exists())

    open_folder_if_supported(output_root)


def main() -> None:
    write_project_readme(KQK_OUTPUT_ROOT)


if __name__ == "__main__":
    main()