from pathlib import Path
import os


KPK_OUTPUT_ROOT = Path(r"C:\Users\Κωνσταντίνος\Desktop\KPK Dataset")


def write_project_readme(output_root: Path) -> None:
    output_root.mkdir(parents=True, exist_ok=True)

    readme_path = output_root / "README.md"

    readme_lines = [
        "# KPK Endgame Analysis — WDL Rule Extraction with Decision Trees",
        "",
        "Αυτός ο φάκελος περιέχει την πλήρη πειραματική ενότητα για το σκακιστικό φινάλε **KPK**.",
        "",
        "Το KPK endgame αποτελείται από:",
        "",
        "- λευκό βασιλιά,",
        "- λευκό πιόνι,",
        "- μαύρο βασιλιά.",
        "",
        "Σε αντίθεση με τα KRK και KQK πειράματα, εδώ το βασικό πρόβλημα δεν είναι η ταξινόμηση DTZ φάσεων μετατροπής.",
        "",
        "Το KPK αντιμετωπίζεται ως **WDL binary classification problem**:",
        "",
        "- `Draw`: η θέση δεν είναι κερδισμένη για τον λευκό.",
        "- `Win`: η θέση είναι κερδισμένη για τον λευκό.",
        "",
        "Ο στόχος δεν είναι μόνο η ταξινόμηση θέσεων σε `Win` / `Draw`, αλλά κυρίως η παραγωγή ερμηνεύσιμων κανόνων από Syzygy tablebase δεδομένα με χρήση decision trees.",
        "",
        "---",
        "",
        "## 1. Δομή project",
        "",
        "KPK Dataset/",
        "├── 01_dataset/",
        "│   ├── kpk_exhaustive_wdl_dataset.csv",
        "│   └── kpk_dataset_overview.csv",
        "│",
        "├── 02_model_wdl/",
        "│   ├── kpk_wdl_decision_tree_main_model_summary.csv",
        "│   ├── kpk_wdl_decision_tree_main_model_importances.csv",
        "│   ├── kpk_wdl_decision_tree_confusion_matrix.csv",
        "│   ├── kpk_wdl_decision_tree_multi_seed_raw_results.csv",
        "│   ├── kpk_wdl_decision_tree_multi_seed_stability_summary.csv",
        "│   ├── kpk_wdl_decision_tree_depth_selection_scores.csv",
        "│   ├── kpk_wdl_decision_tree_selected_optimal_depth.csv",
        "│   ├── kpk_wdl_decision_tree_all_leaf_rules.csv",
        "│   ├── kpk_wdl_decision_tree_important_rules.csv",
        "│   ├── kpk_wdl_decision_tree_raw_errors.csv",
        "│   ├── kpk_wdl_decision_tree_categorized_errors.csv",
        "│   ├── kpk_wdl_decision_tree_error_category_counts.csv",
        "│   ├── kpk_wdl_decision_tree_error_type_counts.csv",
        "│   ├── kpk_wdl_decision_tree_errors_by_steps.csv",
        "│   ├── kpk_wdl_decision_tree_tree_rules.txt",
        "│   └── kpk_wdl_decision_tree_summary_report.md",
        "│",
        "├── 03_feature_set_comparison/",
        "│   ├── kpk_wdl_feature_set_comparison_main_config_used.csv",
        "│   ├── kpk_wdl_feature_set_comparison_raw_results.csv",
        "│   ├── kpk_wdl_feature_set_comparison_stability_summary.csv",
        "│   ├── kpk_wdl_feature_set_comparison_main_depth{depth}_{class_weight}_comparison.csv",
        "│   ├── kpk_wdl_feature_set_comparison_raw_importances.csv",
        "│   ├── kpk_wdl_feature_set_comparison_mean_importances.csv",
        "│   ├── kpk_wdl_feature_set_comparison_error_categories_raw.csv",
        "│   └── kpk_wdl_feature_set_comparison_error_category_summary.csv",
        "│",
        "├── 04_figures/",
        "│   ├── kpk_wdl_dataset_distribution.png",
        "│   ├── kpk_wdl_decision_tree_top3.png",
        "│   ├── kpk_wdl_feature_importances.png",
        "│   ├── kpk_wdl_confusion_matrix.png",
        "│   ├── kpk_wdl_error_categories.png",
        "│   ├── kpk_wdl_feature_set_comparison.png",
        "│   └── kpk_wdl_stability_across_depths.png",
        "│",
        "├── 05_rule_consolidation/",
        "│   ├── kpk_wdl_rule_consolidation_leaves_with_signature.csv",
        "│   ├── kpk_wdl_rule_consolidation_distinct_signatures.csv",
        "│   ├── kpk_wdl_rule_consolidation_top_signatures_by_result.csv",
        "│   ├── kpk_wdl_rule_consolidation_interpretive_motifs.csv",
        "│   ├── kpk_wdl_rule_consolidation_result_coverage.csv",
        "│   └── kpk_wdl_rule_consolidation_summary.md",
        "│",
        "└── README.md",
        "",
        "---",
        "",
        "## 2. Σειρά εκτέλεσης",
        "",
        "Τα scripts εκτελούνται με την εξής σειρά:",
        "",
        "```bash",
        "python KPKGenerator.py",
        "python KPKDecTree.py",
        "python KPKComp.py",
        "python KPKVisual.py",
        "python KPKRuleConsolidation.py",
        "python KPKReadMe.py",
        "```",
        "",
        "Το `KPKDecTree.py` πρέπει να εκτελεστεί πριν από τα `KPKComp.py` και `KPKVisual.py`, επειδή παράγει το αρχείο:",
        "",
        "02_model_wdl/kpk_wdl_decision_tree_selected_optimal_depth.csv",
        "",
        "Το αρχείο αυτό καθορίζει το main configuration που χρησιμοποιούν τα επόμενα scripts.",
        "",
        "---",
        "",
        "## 3. Dataset Generation",
        "",
        "Script:",
        "",
        "KPKGenerator.py",
        "",
        "Παράγει exhaustive canonical KPK dataset με χρήση Syzygy tablebases.",
        "",
        "Βασικά outputs:",
        "",
        "01_dataset/kpk_exhaustive_wdl_dataset.csv",
        "01_dataset/kpk_dataset_overview.csv",
        "",
        "Το dataset περιλαμβάνει:",
        "",
        "- FEN θέσης,",
        "- side to move,",
        "- γεωμετρικά χαρακτηριστικά,",
        "- σκακιστικά KPK χαρακτηριστικά,",
        "- opposition/support χαρακτηριστικά,",
        "- Syzygy WDL label,",
        "- binary target `white_is_winning`.",
        "",
        "Το target ορίζεται ως:",
        "",
        "white_is_winning = 1  → Win για τον λευκό",
        "white_is_winning = 0  → Draw",
        "",
        "Το dataset περιέχει και κερδισμένες και ισόπαλες θέσεις. Η μεταβλητή `white_is_winning` είναι απλώς το binary target του μοντέλου.",
        "",
        "Η παραγωγή χρησιμοποιεί canonical horizontal symmetry:",
        "",
        "USE_CANONICAL_SYMMETRY = True",
        "",
        "Άρα τα συμμετρικά pawn files e-h αντιστοιχίζονται στα files d-a, ώστε να μειωθεί ο αριθμός ισοδύναμων θέσεων.",
        "",
        "---",
        "",
        "## 4. WDL Decision Tree Model",
        "",
        "Script:",
        "",
        "KPKDecTree.py",
        "",
        "Εκπαιδεύει decision tree για την πρόβλεψη του target:",
        "",
        "white_is_winning",
        "",
        "Το μοντέλο δεν χρησιμοποιεί πλέον hardcoded main depth. Όπως στα KRK/KQK, πραγματοποιείται multi-seed αξιολόγηση και automatic model selection.",
        "",
        "Η επιλογή main configuration γίνεται με adjusted score:",
        "",
        "adjusted_score = balanced_accuracy_mean - complexity_penalty",
        "",
        "όπου το `complexity_penalty` εξαρτάται από τον μέσο αριθμό leaves.",
        "",
        "Το selected configuration αποθηκεύεται στο:",
        "",
        "02_model_wdl/kpk_wdl_decision_tree_selected_optimal_depth.csv",
        "",
        "Το main model εκπαιδεύεται με το επιλεγμένο:",
        "",
        "max_depth",
        "class_weight",
        "",
        "και όχι με σταθερά χειροκίνητη επιλογή.",
        "",
        "Βασικά outputs:",
        "",
        "kpk_wdl_decision_tree_main_model_summary.csv",
        "kpk_wdl_decision_tree_main_model_importances.csv",
        "kpk_wdl_decision_tree_confusion_matrix.csv",
        "kpk_wdl_decision_tree_all_leaf_rules.csv",
        "kpk_wdl_decision_tree_important_rules.csv",
        "kpk_wdl_decision_tree_summary_report.md",
        "",
        "---",
        "",
        "## 5. Feature Set Comparison",
        "",
        "Script:",
        "",
        "KPKComp.py",
        "",
        "Συγκρίνει τρία feature sets, με δομή αντίστοιχη των KRK/KQK:",
        "",
        "### 5.1 Raw Coordinates",
        "",
        "raw_coordinates",
        "",
        "Περιλαμβάνει:",
        "",
        "side_to_move",
        "wk_file, wk_rank",
        "wp_file, wp_rank",
        "bk_file, bk_rank",
        "",
        "Τα raw coordinates ανακατασκευάζονται από το FEN, ώστε να μη χρειάζεται να αποθηκεύονται υποχρεωτικά στο dataset.",
        "",
        "### 5.2 Geometric Features",
        "",
        "geometric_features",
        "",
        "Περιλαμβάνει:",
        "",
        "side_to_move",
        "steps_to_promotion",
        "is_rook_pawn",
        "black_king_ahead_of_pawn",
        "white_king_pawn_distance",
        "black_king_pawn_distance",
        "pawn_distance_diff",
        "kings_distance",
        "",
        "### 5.3 Full KPK Strategic Features",
        "",
        "full_kpk_strategic_features",
        "",
        "Περιλαμβάνει όλα τα geometric features και επιπλέον:",
        "",
        "black_king_inside_square_of_pawn",
        "black_king_can_block_promotion",
        "white_wins_key_square_race",
        "kings_have_direct_opposition",
        "kings_have_distant_opposition",
        "white_king_strongly_supports_pawn",
        "",
        "Το `KPKComp.py` διαβάζει το selected config από:",
        "",
        "02_model_wdl/kpk_wdl_decision_tree_selected_optimal_depth.csv",
        "",
        "και γράφει το configuration που χρησιμοποιήθηκε στο:",
        "",
        "03_feature_set_comparison/kpk_wdl_feature_set_comparison_main_config_used.csv",
        "",
        "με στήλες:",
        "",
        "main_depth",
        "main_class_weight",
        "source",
        "",
        "---",
        "",
        "## 6. Visualizations",
        "",
        "Script:",
        "",
        "KPKVisual.py",
        "",
        "Παράγει figures για παρουσίαση και ενσωμάτωση στη διπλωματική.",
        "",
        "Το Visual module διαβάζει το ίδιο selected configuration με το Comp και επανεκπαιδεύει το main tree μόνο για visualization.",
        "",
        "Βασικά outputs:",
        "",
        "04_figures/kpk_wdl_dataset_distribution.png",
        "04_figures/kpk_wdl_decision_tree_top3.png",
        "04_figures/kpk_wdl_feature_importances.png",
        "04_figures/kpk_wdl_confusion_matrix.png",
        "04_figures/kpk_wdl_error_categories.png",
        "04_figures/kpk_wdl_feature_set_comparison.png",
        "04_figures/kpk_wdl_stability_across_depths.png",
        "",
        "Στο feature-set comparison εμφανίζονται πλέον:",
        "",
        "Raw Coordinates",
        "Geometric",
        "Full KPK Strategic",
        "",
        "---",
        "",
        "## 7. Rule Extraction",
        "",
        "Το `KPKDecTree.py` εξάγει όλα τα leaf rules στο:",
        "",
        "02_model_wdl/kpk_wdl_decision_tree_all_leaf_rules.csv",
        "",
        "και τα σημαντικότερα rules στο:",
        "",
        "02_model_wdl/kpk_wdl_decision_tree_important_rules.csv",
        "",
        "Κάθε extracted rule περιλαμβάνει:",
        "",
        "- `predicted_label`: 0 για Draw, 1 για Win.",
        "- `predicted_result`: Draw / Win.",
        "- `samples`: αριθμός samples στο leaf.",
        "- `purity`: καθαρότητα leaf.",
        "- `technical_rule`: ακριβής decision-tree συνθήκη.",
        "- `readable_rule`: technical rule με πιο αναγνώσιμα feature names.",
        "- `human_readable_rule`: φυσική γλωσσική απόδοση του κανόνα.",
        "- `rule_summary`: σύντομη σκακιστική ερμηνεία.",
        "",
        "---",
        "",
        "## 8. Rule Consolidation",
        "",
        "Script:",
        "",
        "KPKRuleConsolidation.py",
        "",
        "Επειδή το KPK είναι WDL binary classification, το consolidation γίνεται με:",
        "",
        "predicted_result + binned_signature",
        "",
        "όπου:",
        "",
        "- `predicted_result`: Draw / Win.",
        "- `binned_signature`: coarse grouping των feature conditions του leaf.",
        "",
        "Βασικά outputs:",
        "",
        "05_rule_consolidation/kpk_wdl_rule_consolidation_leaves_with_signature.csv",
        "05_rule_consolidation/kpk_wdl_rule_consolidation_distinct_signatures.csv",
        "05_rule_consolidation/kpk_wdl_rule_consolidation_top_signatures_by_result.csv",
        "05_rule_consolidation/kpk_wdl_rule_consolidation_interpretive_motifs.csv",
        "05_rule_consolidation/kpk_wdl_rule_consolidation_result_coverage.csv",
        "05_rule_consolidation/kpk_wdl_rule_consolidation_summary.md",
        "",
        "Τα βασικά interpretive motifs είναι KPK-specific και περιλαμβάνουν:",
        "",
        "### Win motifs",
        "",
        "win_promotion_race_signature",
        "win_key_square_race_signature",
        "win_key_square_and_support_signature",
        "win_black_outside_square_signature",
        "win_no_blockade_signature",
        "win_key_square_race_only_signature",
        "win_strong_king_support_signature",
        "win_strong_support_only_signature",
        "win_advanced_non_rook_pawn_signature",
        "win_opposition_tempo_signature",
        "win_white_to_move_tempo_signature",
        "win_other_data_signature",
        "",
        "### Draw motifs",
        "",
        "draw_rook_pawn_exception_signature",
        "draw_square_rule_and_blockade_signature",
        "draw_promotion_blockade_signature",
        "draw_square_rule_signature",
        "draw_black_king_ahead_signature",
        "draw_opposition_tempo_signature",
        "draw_other_data_signature",
        "",
        "Το `other_data_signature` παραμένει ως fallback motif, ώστε να φαίνεται ποιο μέρος των rules δεν καλύπτεται από τα προκαθορισμένα KPK motifs.",
        "",
        "Οι consolidated πίνακες χρησιμοποιούν ονοματοδοσία κοντά στα KRK/KQK:",
        "",
        "n_signatures",
        "n_leaves",
        "total_samples",
        "mean_samples",
        "mean_purity",
        "min_purity",
        "max_purity",
        "coverage_pct",
        "",
        "---",
        "",
        "## 9. Error Analysis",
        "",
        "Τα λάθη κατηγοριοποιούνται σε diagnostic KPK motifs.",
        "",
        "Για false positive predictions, δηλαδή όταν το μοντέλο προβλέπει Win ενώ η θέση είναι Draw, χρησιμοποιούνται κατηγορίες όπως:",
        "",
        "rook_pawn_draw_missed",
        "square_rule_draw_missed",
        "promotion_blockade_draw_missed",
        "black_king_ahead_draw_missed",
        "opposition_tempo_draw_missed",
        "other_false_positive_win_prediction",
        "",
        "Για false negative predictions, δηλαδή όταν το μοντέλο προβλέπει Draw ενώ η θέση είναι Win, χρησιμοποιούνται κατηγορίες όπως:",
        "",
        "key_square_win_missed",
        "promotion_race_win_missed",
        "advanced_non_rook_pawn_win_missed",
        "white_king_support_win_missed",
        "opposition_tempo_win_missed",
        "strong_king_support_win_missed",
        "other_false_negative_draw_prediction",
        "",
        "Αυτές οι κατηγορίες είναι diagnostic labels. Δεν αποτελούν τυπικές σκακιστικές αποδείξεις.",
        "",
        "---",
        "",
        "## 10. Μεθοδολογία Αξιολόγησης",
        "",
        "Το μοντέλο αξιολογείται με:",
        "",
        "- accuracy,",
        "- balanced accuracy,",
        "- macro F1,",
        "- weighted F1,",
        "- confusion matrix,",
        "- cross-validation,",
        "- multi-seed stability,",
        "- error category analysis,",
        "- feature set comparison,",
        "- rule consolidation.",
        "",
        "Το βασικό metric που τονίζεται είναι το `balanced accuracy`, επειδή οι δύο κλάσεις `Draw` και `Win` δεν είναι απαραίτητα απόλυτα ισορροπημένες.",
        "",
        "Η multi-seed αξιολόγηση χρησιμοποιεί:",
        "",
        "seeds = [42, 123, 456]",
        "depths = [7, 9, 12]",
        "class_weight = [None, balanced]",
        "",
        "---",
        "",
        "## 11. Αναπαραγωγιμότητα",
        "",
        "Τα βασικά CSV αρχεία αποθηκεύονται με:",
        "",
        "encoding = utf-8-sig",
        "separator = ;",
        "decimal = ,",
        "float_format = 4 decimal places",
        "",
        "Η ανάγνωση των CSV γίνεται με `read_csv_auto`, ώστε να υποστηρίζονται τόσο semicolon-separated αρχεία όσο και παλιότερα comma-separated αρχεία.",
        "",
        "Τα train/test splits είναι stratified.",
        "",
        "Οι βασικές tree ρυθμίσεις είναι:",
        "",
        "criterion = gini",
        "min_samples_split = 50",
        "min_samples_leaf = 25",
        "",
        "Το τελικό `max_depth` και `class_weight` επιλέγονται αυτόματα από το depth/class-weight grid.",
        "",
        "---",
        "",
        "## 12. Κύρια Ερμηνεία για τη Διπλωματική",
        "",
        "Τα KPK πειράματα δείχνουν ότι:",
        "",
        "1. Τα raw coordinates αποτελούν απλό baseline.",
        "2. Τα geometric features βελτιώνουν την ερμηνευσιμότητα και δίνουν βασική σκακιστική δομή.",
        "3. Τα full strategic KPK features προσθέτουν έννοιες όπως square of the pawn, blockade, key-square race, opposition και king support.",
        "4. Τα decision trees μπορούν να εξάγουν ερμηνεύσιμους Win/Draw κανόνες από Syzygy-labeled KPK θέσεις.",
        "5. Το rule consolidation συγκεντρώνει τα πολλά leaf rules σε μικρότερο αριθμό KPK motifs.",
        "",
        "Το KPK λειτουργεί ως WDL case study, ενώ τα KRK/KQK λειτουργούν ως DTZ phase-classification case studies.",
        "",
        "---",
        "",
        "## 13. Προειδοποίηση Ερμηνείας",
        "",
        "Οι κανόνες που εξάγονται από το decision tree είναι machine-learned approximations.",
        "",
        "Πρέπει να ερμηνεύονται ως ερμηνεύσιμοι κανόνες που έμαθε το μοντέλο από tablebase δεδομένα και όχι ως τυπικά σκακιστικά θεωρήματα.",
        "",
        "Οι handcrafted features όπως `black_king_can_block_promotion`, `white_wins_key_square_race` και `white_king_strongly_supports_pawn` είναι σκακιστικά εμπνευσμένες προσεγγίσεις. Δεν αντικαθιστούν το Syzygy label, αλλά βοηθούν το decision tree να παράγει πιο ερμηνεύσιμους κανόνες.",
    ]

    readme = "\n".join(readme_lines)

    readme_path.write_text(readme, encoding="utf-8")

    print("README saved successfully.")
    print("Path:")
    print(readme_path)
    print("Exists:", readme_path.exists())

    try:
        os.startfile(output_root)
    except Exception:
        pass


def main() -> None:
    write_project_readme(KPK_OUTPUT_ROOT)


if __name__ == "__main__":
    main()
