from __future__ import annotations

import os
import sys
from pathlib import Path


KRK_OUTPUT_ROOT = Path(r"C:\Users\Κωνσταντίνος\Desktop\KRK Dataset")


def open_folder_if_supported(folder: Path) -> None:
    """Open the output folder in the OS file manager if running on Windows."""
    if sys.platform.startswith("win") and hasattr(os, "startfile"):
        os.startfile(folder)


def write_project_readme(output_root: Path) -> None:
    output_root.mkdir(parents=True, exist_ok=True)
    readme_path = output_root / "README.md"

    readme_lines = [
        "# KRK Endgame Analysis — Παραγωγή Κανόνων με Decision Trees",
        "",
        "Αυτός ο φάκελος περιέχει την πλήρη πειραματική ενότητα για το σκακιστικό φινάλε **KRK**.",
        "",
        "Το KRK endgame αποτελείται από:",
        "",
        "- λευκό βασιλιά,",
        "- λευκό πύργο,",
        "- μαύρο βασιλιά.",
        "",
        "Ο στόχος της ενότητας δεν είναι η απλή ταξινόμηση θέσεων ως `Win` / `Draw`, αλλά η παραγωγή ερμηνεύσιμων κανόνων που περιγράφουν τη φάση μετατροπής μιας κερδισμένης KRK θέσης.",
        "",
        "Για αυτόν τον λόγο χρησιμοποιείται το `DTZ` από Syzygy tablebases και μετατρέπεται σε προσεγγιστικές φάσεις μετατροπής.",
        "",
        "",
        "## 1. Στόχος της KRK ενότητας",
        "",
        "Στο KRK, η WDL πληροφορία είναι σχετικά φτωχή για rule extraction, επειδή οι περισσότερες νόμιμες θέσεις με λευκό πύργο και λευκό βασιλιά εναντίον μαύρου βασιλιά είναι θεωρητικά κερδισμένες για τον λευκό.",
        "",
        "Επομένως, αντί να προβλέπεται απλώς αν η θέση είναι κερδισμένη, το πρόβλημα μετατρέπεται σε ταξινόμηση της θέσης σε φάση μετατροπής:",
        "",
        "- `long_conversion`,",
        "- `medium_conversion`,",
        "- `short_conversion`,",
        "- `immediate_mate_or_near`.",
        "",
        "Οι φάσεις αυτές χρησιμοποιούνται ως πρακτικά labels για interpretable classification και rule extraction.",
        "",
        "",
        "## 2. DTZ-derived distance και όχι πραγματικό DTM",
        "",
        "Η στήλη `dtz_abs` είναι η απόλυτη τιμή του Syzygy DTZ.",
        "",
        "Επιπλέον, το dataset περιλαμβάνει και τη στήλη `mate_moves`, η οποία υπολογίζεται ως:",
        "",
        "mate_moves = (dtz_abs + 1) // 2",
        "",
        "Η ποσότητα αυτή δεν αποτελεί επίσημο DTM label. Πρέπει να ερμηνεύεται ως **DTZ-derived approximate conversion distance**.",
        "",
        "Στο KRK τα βασικά buckets παραμένουν ορισμένα με άμεσα DTZ thresholds:",
        "",
        "immediate_mate_or_near : DTZ 1–2",
        "short_conversion       : DTZ 3–8",
        "medium_conversion      : DTZ 9–16",
        "long_conversion        : DTZ 17+",
        "",
        "Οι κατηγορίες αυτές είναι πειραματική διακριτοποίηση του DTZ και όχι επίσημες σκακιστικές κατηγορίες.",
        "",
        "",
        "## 3. Dataset policy",
        "",
        "Το dataset παράγεται για:",
        "",
        "side_to_move = White",
        "only_winning_for_side_to_move = True",
        "",
        "Δηλαδή κρατούνται μόνο θέσεις στις οποίες η πλευρά που έχει την κίνηση, εδώ ο λευκός, είναι κερδισμένη σύμφωνα με τις Syzygy tablebases.",
        "",
        "Αυτό γίνεται επειδή ο στόχος δεν είναι WDL classification όλων των θέσεων, αλλά phase classification κερδισμένων KRK θέσεων.",
        "",
        "Αν περιλαμβάνονταν μη κερδισμένες θέσεις, τότε τα DTZ buckets δεν θα είχαν καθαρή ερμηνεία ως φάσεις μετατροπής προς το mate.",
        "",
        "",
        "## 4. Δομή project",
        "",
        "KRK Dataset/",
        "├── 01_dataset/",
        "│   ├── krk_exhaustive_dtz_dataset.csv",
        "│   └── krk_dataset_overview.csv",
        "│",
        "├── 02_model_dtz/",
        "│   ├── krk_dtz_decision_tree_main_model_summary.csv",
        "│   ├── krk_dtz_decision_tree_main_model_importances.csv",
        "│   ├── krk_dtz_decision_tree_confusion_matrix.csv",
        "│   ├── krk_dtz_decision_tree_multi_seed_raw_results.csv",
        "│   ├── krk_dtz_decision_tree_multi_seed_stability_summary.csv",
        "│   ├── krk_dtz_decision_tree_depth_selection_scores.csv",
        "│   ├── krk_dtz_decision_tree_selected_optimal_depth.csv",
        "│   ├── krk_dtz_decision_tree_all_leaf_rules.csv",
        "│   ├── krk_dtz_decision_tree_important_rules.csv",
        "│   ├── krk_dtz_decision_tree_raw_errors.csv",
        "│   ├── krk_dtz_decision_tree_categorized_errors.csv",
        "│   ├── krk_dtz_decision_tree_error_category_counts.csv",
        "│   ├── krk_dtz_decision_tree_error_type_counts.csv",
        "│   ├── krk_dtz_decision_tree_error_flag_counts.csv",
        "│   ├── krk_dtz_decision_tree_error_severity_counts.csv",
        "│   ├── krk_dtz_decision_tree_phase_confusion_counts.csv",
        "│   ├── krk_dtz_decision_tree_errors_by_dtz_abs.csv",
        "│   ├── krk_dtz_decision_tree_errors_by_mate_moves.csv",
        "│   ├── krk_dtz_decision_tree_tree_rules.txt",
        "│   └── krk_dtz_decision_tree_summary_report.md",
        "│",
        "├── 03_feature_set_comparison/",
        "│   ├── krk_feature_set_comparison_raw_results.csv",
        "│   ├── krk_feature_set_comparison_stability_summary.csv",
        "│   ├── krk_feature_set_comparison_main_depth{N}_{class_weight}_comparison.csv",
        "│   ├── krk_feature_set_comparison_main_config_used.csv",
        "│   ├── krk_feature_set_comparison_raw_importances.csv",
        "│   ├── krk_feature_set_comparison_mean_importances.csv",
        "│   ├── krk_feature_set_comparison_error_categories_raw.csv",
        "│   └── krk_feature_set_comparison_error_category_summary.csv",
        "│",
        "├── 04_figures/",
        "│   ├── krk_dataset_distribution.png",
        "│   ├── krk_decision_tree_top3.png",
        "│   ├── krk_feature_importances.png",
        "│   ├── krk_confusion_matrix.png",
        "│   ├── krk_phase_confusion_counts.png",
        "│   ├── krk_error_categories.png",
        "│   ├── krk_error_severity.png",
        "│   ├── krk_errors_by_dtz_abs.png",
        "│   ├── krk_errors_by_mate_moves.png",
        "│   ├── krk_feature_set_comparison.png",
        "│   └── krk_stability_across_depths.png",
        "│",
        "├── 05_rule_consolidation/",
        "│   ├── krk_rule_consolidation_leaves_with_signature.csv",
        "│   ├── krk_rule_consolidation_distinct_signatures.csv",
        "│   ├── krk_rule_consolidation_top_signatures_by_phase.csv",
        "│   ├── krk_rule_consolidation_interpretive_motifs.csv",
        "│   ├── krk_rule_consolidation_phase_coverage.csv",
        "│   └── krk_rule_consolidation_summary.md",
        "│",
        "└── README.md",
        "",
        "",
        "## 5. Σειρά εκτέλεσης",
        "",
        "Τα scripts εκτελούνται με την εξής σειρά:",
        "",
        "```bash",
        "python KRKGenerator.py",
        "python KRKDecTree.py",
        "python KRKComp.py",
        "python KRKVisual.py",
        "python KRKRuleConsolidation.py",
        "python KRKReadMe.py",
        "```",
        "",
        "Η σειρά είναι σημαντική.",
        "",
        "- Το `KRKGenerator.py` παράγει το dataset.",
        "- Το `KRKDecTree.py` εκπαιδεύει το main model και αποθηκεύει το selected configuration.",
        "- Το `KRKComp.py` διαβάζει το selected configuration και συγκρίνει feature sets.",
        "- Το `KRKVisual.py` διαβάζει επίσης το selected configuration και παράγει figures για το ίδιο μοντέλο.",
        "- Το `KRKRuleConsolidation.py` διαβάζει τα extracted leaves και παράγει binned signatures.",
        "- Το `KRKReadMe.py` εκτελείται τελευταίο για να γράψει το τελικό README.",
        "",
        "",
        "## 6. Dataset Generation",
        "",
        "Script:",
        "",
        "`KRKGenerator.py`",
        "",
        "Παράγει exhaustive KRK dataset με χρήση Syzygy tablebases.",
        "",
        "Βασικά outputs:",
        "",
        "- `01_dataset/krk_exhaustive_dtz_dataset.csv`",
        "- `01_dataset/krk_dataset_overview.csv`",
        "",
        "Το dataset περιλαμβάνει:",
        "",
        "- FEN θέσης,",
        "- Syzygy WDL,",
        "- Syzygy DTZ,",
        "- απόλυτη τιμή DTZ (`dtz_abs`),",
        "- DTZ-derived approximate distance (`mate_moves`),",
        "- target phase (`dtz_bucket`),",
        "- γεωμετρικά features,",
        "- chess-informed KRK features για περιορισμό του μαύρου βασιλιά, συνεργασία του λευκού βασιλιά και λειτουργία του πύργου.",
        "",
        "",
        "## 7. Τελικό Feature Set",
        "",
        "Το τελικό KRK main model χρησιμοποιεί τα εξής features:",
        "",
        "bk_legal_moves_if_black_to_move",
        "bk_distance_to_corner",
        "bk_distance_to_edge",
        "bk_in_mating_zone",
        "wk_distance_to_edge",
        "wk_bk_chebyshev_distance",
        "wk_bk_manhattan_distance",
        "kings_in_direct_opposition",
        "wr_bk_file_distance",
        "wr_bk_rank_distance",
        "rook_cuts_off_black_king",
        "",
        "",
        "## 8. Περιγραφή βασικών KRK features",
        "",
        "- `bk_legal_moves_if_black_to_move`: αριθμός νόμιμων κινήσεων του μαύρου βασιλιά αν είχε τη σειρά.",
        "- `bk_distance_to_corner`: απόσταση του μαύρου βασιλιά από την κοντινότερη γωνία.",
        "- `bk_distance_to_edge`: απόσταση του μαύρου βασιλιά από την κοντινότερη άκρη.",
        "- `bk_in_mating_zone`: boolean feature που δείχνει αν ο μαύρος βασιλιάς είναι στην άκρη ή κοντά σε γωνία.",
        "- `wk_distance_to_edge`: απόσταση του λευκού βασιλιά από άκρη.",
        "- `wk_bk_chebyshev_distance`: Chebyshev απόσταση μεταξύ των δύο βασιλιάδων.",
        "- `wk_bk_manhattan_distance`: Manhattan απόσταση μεταξύ των δύο βασιλιάδων.",
        "- `kings_in_direct_opposition`: boolean feature που δείχνει αν οι βασιλιάδες βρίσκονται σε άμεση opposition.",
        "- `wr_bk_file_distance`: απόσταση πύργου και μαύρου βασιλιά σε files.",
        "- `wr_bk_rank_distance`: απόσταση πύργου και μαύρου βασιλιά σε ranks.",
        "- `rook_cuts_off_black_king`: boolean feature που δείχνει αν ο πύργος δημιουργεί γραμμή περιορισμού απέναντι στον μαύρο βασιλιά.",
        "",
        "Τα `bk_in_mating_zone`, `rook_cuts_off_black_king` και `kings_in_direct_opposition` είναι chess-informed features. Δεν αποτελούν Syzygy labels· είναι ερμηνεύσιμα χαρακτηριστικά που συμπυκνώνουν γνωστές στρατηγικές έννοιες του KRK.",
        "",
        "",
        "## 9. Main Decision Tree Model",
        "",
        "Script:",
        "",
        "`KRKDecTree.py`",
        "",
        "Εκπαιδεύει decision tree για ταξινόμηση των KRK θέσεων στις τέσσερις DTZ-derived φάσεις.",
        "",
        "Σταθερές ρυθμίσεις:",
        "",
        "seed = 42",
        "criterion = gini",
        "min_samples_split = 50",
        "min_samples_leaf = 25",
        "",
        "Το `max_depth` και το `class_weight` δεν είναι hardcoded. Επιλέγονται αυτόματα από grid:",
        "",
        "max_depth: [7, 9, 12]",
        "class_weight: [None, balanced]",
        "",
        "Η επιλογή γίνεται με adjusted score:",
        "",
        "adjusted_score = balanced_accuracy_mean − penalty_weight × sqrt(n_leaves_mean / max_n_leaves_mean)",
        "",
        "Το score επιβραβεύει υψηλή balanced accuracy και ποινικοποιεί την πολυπλοκότητα του δέντρου, ώστε να προτιμώνται πιο ερμηνεύσιμα μοντέλα όταν η επίδοση είναι παρόμοια.",
        "",
        "Η παράμετρος `penalty_weight = 0.01` είναι heuristic επιλογή για model selection και όχι θεωρητικό metric.",
        "",
        "Το selected configuration αποθηκεύεται στο:",
        "",
        "- `02_model_dtz/krk_dtz_decision_tree_selected_optimal_depth.csv`",
        "",
        "Αυτό το αρχείο διαβάζεται από τα `KRKComp.py` και `KRKVisual.py`, ώστε όλο το pipeline να χρησιμοποιεί το ίδιο main configuration.",
        "",
        "",
        "## 10. Μεθοδολογική σημείωση για model selection",
        "",
        "Η επιλογή του main model βασίζεται σε multi-seed evaluation και adjusted score.",
        "",
        "Για λόγους διαφάνειας, το pipeline αναφέρει επίσης cross-validation metrics:",
        "",
        "- CV accuracy,",
        "- CV balanced accuracy,",
        "- CV macro F1.",
        "",
        "Το single-split test score πρέπει να ερμηνεύεται ως diagnostic/secondary ένδειξη επίδοσης και όχι ως μοναδική ανεξάρτητη benchmark μέτρηση.",
        "",
        "Ο κύριος στόχος της ενότητας είναι η παραγωγή και ερμηνεία κανόνων και όχι η παρουσίαση ενός αυστηρού benchmark γενίκευσης.",
        "",
        "",
        "## 11. Ordinal φύση του target",
        "",
        "Οι κλάσεις του `dtz_bucket` έχουν φυσική σειρά:",
        "",
        "long_conversion → medium_conversion → short_conversion → immediate_mate_or_near",
        "",
        "Παρόλα αυτά χρησιμοποιείται `DecisionTreeClassifier` ως nominal classifier.",
        "",
        "Η επιλογή αυτή είναι σκόπιμη, επειδή ο βασικός στόχος είναι η εξαγωγή ανθρώπινα αναγνώσιμων κανόνων ανά φάση και όχι η βελτιστοποίηση ordinal loss.",
        "",
        "Η ordinal φύση του προβλήματος αξιολογείται εκ των υστέρων μέσω phase-distance error analysis, όπου διακρίνονται boundary confusions από large phase confusions.",
        "",
        "",
        "## 12. Feature Set Comparison",
        "",
        "Script:",
        "",
        "`KRKComp.py`",
        "",
        "Συγκρίνει τρία feature sets:",
        "",
        "1. `raw_coordinates`",
        "2. `geometric_features`",
        "3. `full_krk_strategic_features`",
        "",
        "Το `raw_coordinates` αποτελεί baseline με τις απλές συντεταγμένες των κομματιών.",
        "",
        "Το `geometric_features` χρησιμοποιεί αποστάσεις και γεωμετρικές σχέσεις.",
        "",
        "Το `full_krk_strategic_features` προσθέτει chess-informed πληροφορία, όπως κινητικότητα μαύρου βασιλιά, mating zone, opposition και rook cutoff.",
        "",
        "Ο main comparison πίνακας παρουσιάζεται στο ίδιο `(depth, class_weight)` που επέλεξε το `KRKDecTree.py`, ώστε να απομονώνεται η επίδραση των features.",
        "",
        "Το comparison report περιλαμβάνει gains τόσο σε σχέση με το raw-coordinate baseline όσο και σε σχέση με το geometric baseline.",
        "",
        "Το όνομα του main comparison αρχείου είναι δυναμικό, π.χ.:",
        "",
        "krk_feature_set_comparison_main_depth{N}_{class_weight}_comparison.csv",
        "",
        "Παράγεται επίσης:",
        "",
        "- `krk_feature_set_comparison_main_config_used.csv`",
        "",
        "ώστε να καταγράφεται αν το configuration προήλθε αυτόματα από το `KRKDecTree.py` ή από fallback.",
        "",
        "",
        "## 13. Visualizations",
        "",
        "Script:",
        "",
        "`KRKVisual.py`",
        "",
        "Παράγει εικόνες για παρουσίαση:",
        "",
        "- κατανομή buckets και DTZ-derived approximate distance,",
        "- top levels του decision tree,",
        "- feature importances,",
        "- confusion matrix,",
        "- phase confusions,",
        "- error categories,",
        "- error severity,",
        "- errors by DTZ absolute value,",
        "- errors by approximate mate moves,",
        "- feature-set comparison,",
        "- stability across depths.",
        "",
        "Το `KRKVisual.py` διαβάζει το selected configuration από το `KRKDecTree.py`.",
        "",
        "Έτσι το visualized tree, το feature-set comparison figure και το stability plot αντιστοιχούν στο ίδιο main model configuration.",
        "",
        "Το πλήρες decision tree δεν είναι πρακτικά ευανάγνωστο, επομένως στις οπτικοποιήσεις παρουσιάζονται μόνο τα ανώτερα επίπεδα.",
        "",
        "",
        "## 14. Παραγόμενοι Κανόνες",
        "",
        "Τα σημαντικότερα αρχεία για την παραγωγή κανόνων είναι:",
        "",
        "- `02_model_dtz/krk_dtz_decision_tree_important_rules.csv`",
        "- `02_model_dtz/krk_dtz_decision_tree_all_leaf_rules.csv`",
        "",
        "Κάθε κανόνας περιλαμβάνει:",
        "",
        "- `technical_rule`: ακριβής κανόνας του decision tree με thresholds.",
        "- `readable_rule`: ίδιος κανόνας με πιο αναγνώσιμα feature names.",
        "- `human_readable_rule`: φυσική γλωσσική απόδοση του κανόνα.",
        "- `rule_summary`: σύντομη σκακιστική ερμηνεία του κανόνα.",
        "- `strategic_interpretation`: ερμηνεία της προβλεπόμενης KRK φάσης.",
        "- `strategic_guidance`: στρατηγικός στόχος για τη συγκεκριμένη φάση.",
        "",
        "Οι κανόνες είναι machine-learned approximations από tablebase data και όχι τυπικά σκακιστικά θεωρήματα.",
        "",
        "",
        "## 15. Rule Consolidation — Auto-Extracted Binned Signatures",
        "",
        "Script:",
        "",
        "`KRKRuleConsolidation.py`",
        "",
        "Το decision tree μπορεί να παράγει πολλά leaf rules. Το rule consolidation τα μετατρέπει σε πιο συμπαγή και αναγνώσιμα patterns.",
        "",
        "Η τελική προσέγγιση έχει δύο επίπεδα:",
        "",
        "1. **Objective / data-driven layer**",
        "",
        "   Τα decision-tree leaves μετατρέπονται σε binned signatures. Κάθε signature προκύπτει αυτόματα από τα thresholds του δέντρου και ομαδοποιείται με βάση:",
        "",
        "   predicted_phase + binned_signature",
        "",
        "2. **Interpretive layer**",
        "",
        "   Σε κάθε signature αποδίδεται προαιρετικά ανθρώπινη σκακιστική ερμηνεία, όπως rook cutoff, mating zone, king approach, opposition, edge pressure ή long-zone-but-white-king-far motif.",
        "",
        "Το interpretive label δεν καθορίζει την κύρια ομαδοποίηση. Η κύρια ομαδοποίηση παραμένει data-driven.",
        "",
        "Κύρια outputs:",
        "",
        "- `05_rule_consolidation/krk_rule_consolidation_leaves_with_signature.csv`",
        "- `05_rule_consolidation/krk_rule_consolidation_distinct_signatures.csv`",
        "- `05_rule_consolidation/krk_rule_consolidation_top_signatures_by_phase.csv`",
        "- `05_rule_consolidation/krk_rule_consolidation_interpretive_motifs.csv`",
        "- `05_rule_consolidation/krk_rule_consolidation_phase_coverage.csv`",
        "- `05_rule_consolidation/krk_rule_consolidation_summary.md`",
        "",
        "Για το KRK, τα dominant motifs περιγράφουν κυρίως:",
        "",
        "- πίεση σε άκρη ή γωνία,",
        "- περιορισμένη κινητικότητα του μαύρου βασιλιά,",
        "- οδήγηση ή παρουσία του μαύρου βασιλιά στη mating zone,",
        "- προσέγγιση ή απόσταση του λευκού βασιλιά,",
        "- ενεργό rook cutoff,",
        "- opposition των βασιλιάδων,",
        "- περιπτώσεις όπου ο μαύρος βασιλιάς είναι ήδη στη mating zone αλλά ο λευκός βασιλιάς είναι ακόμη μακριά.",
        "",
        "",
        "## 16. Μεθοδολογία Αξιολόγησης",
        "",
        "Το μοντέλο αξιολογείται με:",
        "",
        "- accuracy,",
        "- balanced accuracy,",
        "- macro F1,",
        "- weighted F1,",
        "- confusion matrix,",
        "- cross-validation metrics,",
        "- multi-seed stability,",
        "- depth/class-weight selection diagnostic,",
        "- error category analysis,",
        "- feature set comparison.",
        "",
        "Το βασικό metric που τονίζεται είναι το `balanced accuracy`, επειδή το `dtz_bucket` target μπορεί να μην είναι ισορροπημένο ανά φάση.",
        "",
        "",
        "## 17. Error Analysis",
        "",
        "Τα λάθη κατηγοριοποιούνται με βάση το αν το μοντέλο προέβλεψε τη θέση πιο κοντά ή πιο μακριά από την τελική μετατροπή σε σχέση με το πραγματικό DTZ bucket.",
        "",
        "Βασικά error types:",
        "",
        "predicted_too_close_to_mate",
        "predicted_too_far_from_mate",
        "",
        "Επιπλέον, υπολογίζεται phase distance:",
        "",
        "phase_distance = predicted_phase_rank - true_phase_rank",
        "absolute_phase_distance = |phase_distance|",
        "",
        "Έτσι διακρίνονται:",
        "",
        "- boundary confusions, όπως `long ↔ medium` ή `short ↔ immediate`,",
        "- large confusions, όπως `long ↔ immediate`.",
        "",
        "Ενδεικτικά diagnostic labels:",
        "",
        "- `long_medium_boundary_confusion`,",
        "- `medium_short_boundary_confusion`,",
        "- `short_immediate_boundary_confusion`,",
        "- `large_phase_confusion`,",
        "- `mating_zone_status_underestimated`,",
        "- `mating_zone_status_overestimated`,",
        "- `direct_opposition_significance_underestimated`,",
        "- `black_king_freedom_overestimated_as_restriction`,",
        "- `edge_distance_overestimated_as_restriction`,",
        "- `corner_distance_overestimated_as_restriction`,",
        "- `white_king_distance_underestimated`,",
        "- `white_king_support_underestimated`,",
        "- `white_king_edge_position_misread`,",
        "- `rook_distance_underestimated`,",
        "- `rook_proximity_underestimated`,",
        "- `rook_cutoff_related_confusion`.",
        "",
        "Οι κατηγορίες αυτές είναι diagnostic labels για ερμηνεία των λαθών και όχι τυπικές σκακιστικές αποδείξεις.",
        "",
        "Τα πιο σημαντικά error-analysis outputs είναι:",
        "",
        "- `krk_dtz_decision_tree_phase_confusion_counts.csv`,",
        "- `krk_dtz_decision_tree_error_severity_counts.csv`,",
        "- `krk_dtz_decision_tree_errors_by_dtz_abs.csv`,",
        "- `krk_dtz_decision_tree_errors_by_mate_moves.csv`.",
        "",
        "",
        "## 18. Κύρια Ερμηνεία για τη Διπλωματική",
        "",
        "Τα KRK πειράματα μπορούν να υποστηρίξουν τα εξής:",
        "",
        "1. Η απλή WDL ταξινόμηση δεν δίνει αρκετά πλούσια πληροφορία για παραγωγή κανόνων στο KRK.",
        "2. Η χρήση DTZ-derived phase buckets επιτρέπει rule extraction για διαφορετικά στάδια τεχνικής μετατροπής.",
        "3. Τα raw coordinates παρέχουν baseline, αλλά τα geometric και chess-informed features είναι πιο κατάλληλα για ερμηνεύσιμους κανόνες.",
        "4. Τα στρατηγικά KRK features αποτυπώνουν περιορισμό του μαύρου βασιλιά, rook cutoff, mating zone, king approach και opposition.",
        "5. Το rule consolidation παράγει πρώτα data-driven binned signatures και μετά optional ανθρώπινα ερμηνευτικά labels.",
        "6. Τα downstream scripts χρησιμοποιούν το ίδιο selected model configuration, ώστε τα metrics, comparisons και figures να είναι μεταξύ τους συνεπή.",
        "7. Τα περισσότερα λάθη αναμένονται ως boundary confusions μεταξύ γειτονικών DTZ phases, επειδή το underlying target είναι συνεχές αλλά έχει διακριτοποιηθεί σε buckets.",
        "",
        "",
        "## 19. Προειδοποίηση Ερμηνείας",
        "",
        "Οι κανόνες που εξάγονται από το decision tree είναι machine-learned approximations.",
        "",
        "Πρέπει να ερμηνεύονται ως ερμηνεύσιμοι κανόνες που έμαθε το μοντέλο από tablebase δεδομένα και όχι ως τυπικά σκακιστικά θεωρήματα.",
        "",
        "Επιπλέον:",
        "",
        "- τα DTZ buckets είναι πειραματική διακριτοποίηση,",
        "- το `mate_moves` είναι DTZ-derived approximation και όχι πραγματικό DTM,",
        "- τα `bk_in_mating_zone`, `rook_cuts_off_black_king` και `kings_in_direct_opposition` είναι handcrafted chess-informed features,",
        "- το decision tree είναι nominal classifier, ενώ η ordinal φύση των phases αξιολογείται post-hoc μέσω phase-distance analysis.",
    ]

    readme = "\n".join(readme_lines)
    readme_path.write_text(readme, encoding="utf-8")

    print("README saved successfully.")
    print("Path:")
    print(readme_path)
    print("Exists:", readme_path.exists())

    open_folder_if_supported(output_root)


def main() -> None:
    write_project_readme(KRK_OUTPUT_ROOT)


if __name__ == "__main__":
    main()
